# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aruco.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='aruco.proto',
  package='aruco',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x61ruco.proto\x12\x05\x61ruco\"\x07\n\x05\x45mpty\"\x17\n\nHelloReply\x12\t\n\x01t\x18\x01 \x01(\x04\"(\n\x05Vec3f\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"J\n\nCoordinate\x12\x17\n\x01r\x18\x01 \x01(\x0b\x32\x0c.aruco.Vec3f\x12\x17\n\x01t\x18\x02 \x01(\x0b\x32\x0c.aruco.Vec3f\x12\n\n\x02st\x18\x03 \x01(\x01\x32\x8d\x01\n\x07Greeter\x12-\n\x08SayHello\x12\x0c.aruco.Empty\x1a\x11.aruco.HelloReply\"\x00\x12(\n\x03\x41sk\x12\x0c.aruco.Empty\x1a\x11.aruco.Coordinate\"\x00\x12)\n\x04Goal\x12\x0c.aruco.Empty\x1a\x11.aruco.Coordinate\"\x00\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='aruco.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=29,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='aruco.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='t', full_name='aruco.HelloReply.t', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=54,
)


_VEC3F = _descriptor.Descriptor(
  name='Vec3f',
  full_name='aruco.Vec3f',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='aruco.Vec3f.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='aruco.Vec3f.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='aruco.Vec3f.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=96,
)


_COORDINATE = _descriptor.Descriptor(
  name='Coordinate',
  full_name='aruco.Coordinate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='r', full_name='aruco.Coordinate.r', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t', full_name='aruco.Coordinate.t', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='st', full_name='aruco.Coordinate.st', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=172,
)

_COORDINATE.fields_by_name['r'].message_type = _VEC3F
_COORDINATE.fields_by_name['t'].message_type = _VEC3F
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['Vec3f'] = _VEC3F
DESCRIPTOR.message_types_by_name['Coordinate'] = _COORDINATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'aruco_pb2'
  # @@protoc_insertion_point(class_scope:aruco.Empty)
  ))
_sym_db.RegisterMessage(Empty)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREPLY,
  __module__ = 'aruco_pb2'
  # @@protoc_insertion_point(class_scope:aruco.HelloReply)
  ))
_sym_db.RegisterMessage(HelloReply)

Vec3f = _reflection.GeneratedProtocolMessageType('Vec3f', (_message.Message,), dict(
  DESCRIPTOR = _VEC3F,
  __module__ = 'aruco_pb2'
  # @@protoc_insertion_point(class_scope:aruco.Vec3f)
  ))
_sym_db.RegisterMessage(Vec3f)

Coordinate = _reflection.GeneratedProtocolMessageType('Coordinate', (_message.Message,), dict(
  DESCRIPTOR = _COORDINATE,
  __module__ = 'aruco_pb2'
  # @@protoc_insertion_point(class_scope:aruco.Coordinate)
  ))
_sym_db.RegisterMessage(Coordinate)



_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='aruco.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=175,
  serialized_end=316,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='aruco.Greeter.SayHello',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_HELLOREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Ask',
    full_name='aruco.Greeter.Ask',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_COORDINATE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Goal',
    full_name='aruco.Greeter.Goal',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_COORDINATE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
